POST http://localhost:7019/SV2/StudentNames/SubTable/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back-logs": "",
  "Roll Number": "",
  "file": "",
  "GitLink": "",
  "KS-Select": ""
}